# Constants

# Colors
RED = (255, 0, 0)
BLUE = (0, 0, 255)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
YELLOW = (255, 255, 0)

# GAME PROPERTIES
WIDTH, HEIGHT = 800, 600
GAME_DURATION = 60000  # 60 seconds

# PLAYER PARTICLE POPERPTIES
PARTICLE_SIZE = 10
PARTICLE_COUNT = 10
PARTICLE_SPEED = 20
PARTICLE_RANGE = 20
PARTICLE_HEALTH = 10
PARITCLE_ATTACK = 1
PARTICLE_DEFENSE = 1

# PLAYER PROPERTIES
PLAYER_ONE = "BD"
PLAYER_ONE_COLOR = BLUE
PLAYER_TWO = "SJ"
PLAYER_TWO_COLOR = RED

# NATURE  
FOOD = "food"
FOOD_COUNT = 7

